import type { ExpoConfig } from "expo/config";

const APP_IDENTIFIER = "com.noirwire.app";
const BASE_COLOUR = "#0b0b0c";

// The New Architecture is the only architecture in this SDK, so there is no
// flag to set for it. Native folders are generated by prebuild and never
// committed.
const config: ExpoConfig = {
  name: "NoirWire",
  slug: "noirwire",
  scheme: "noirwire",
  version: "0.1.0",
  orientation: "portrait",
  userInterfaceStyle: "dark",
  backgroundColor: BASE_COLOUR,
  ios: {
    bundleIdentifier: APP_IDENTIFIER,
    supportsTablet: false,
    userInterfaceStyle: "dark",
    infoPlist: { ITSAppUsesNonExemptEncryption: false },
  },
  android: {
    package: APP_IDENTIFIER,
    userInterfaceStyle: "dark",
  },
  web: { bundler: "metro", output: "single" },
  plugins: [
    "expo-router",
    "expo-font",
    ["expo-splash-screen", { backgroundColor: BASE_COLOUR }],
    [
      "expo-build-properties",
      { ios: { deploymentTarget: "16.4" }, android: { minSdkVersion: 24 } },
    ],
    "react-native-quick-crypto",
  ],
};

export default config;
