import type { ExpoConfig } from "expo/config";

const APP_IDENTIFIER = "com.noirwire.app";
const BASE_COLOUR = "#0b0b0c";

const CAMERA_USAGE = "NoirWire uses the camera only to scan a QR code you point it at.";
const FACE_ID_USAGE = "NoirWire uses Face ID to unlock your wallet when you turn this on.";

// Added by the native template, used by no feature: drawing over other apps
// and reading or writing shared storage. Blocking them strips them from the
// merged manifest, including when a library declares them.
const UNUSED_ANDROID_PERMISSIONS = [
  "android.permission.SYSTEM_ALERT_WINDOW",
  "android.permission.READ_EXTERNAL_STORAGE",
  "android.permission.WRITE_EXTERNAL_STORAGE",
];

// The New Architecture is the only architecture in this SDK, so there is no
// flag to set for it. Native folders are generated by prebuild and never
// committed. The EAS project id is added by `eas init` on first run.
const config: ExpoConfig = {
  name: "NoirWire",
  slug: "noirwire",
  scheme: "noirwire",
  version: "0.1.0",
  orientation: "portrait",
  icon: "./assets/icon.png",
  userInterfaceStyle: "dark",
  backgroundColor: BASE_COLOUR,
  ios: {
    bundleIdentifier: APP_IDENTIFIER,
    supportsTablet: false,
    userInterfaceStyle: "dark",
    infoPlist: { ITSAppUsesNonExemptEncryption: false },
  },
  android: {
    package: APP_IDENTIFIER,
    userInterfaceStyle: "dark",
    adaptiveIcon: {
      foregroundImage: "./assets/adaptive-icon.png",
      backgroundColor: BASE_COLOUR,
    },
    blockedPermissions: UNUSED_ANDROID_PERMISSIONS,
    // The encrypted wallet record must not leave the phone in a cloud or
    // device-to-device backup; the paper phrase is the backup.
    allowBackup: false,
  },
  web: { bundler: "metro", output: "single", favicon: "./assets/favicon.png" },
  plugins: [
    "expo-router",
    "expo-font",
    [
      "expo-splash-screen",
      {
        image: "./assets/splash-icon.png",
        imageWidth: 120,
        resizeMode: "contain",
        backgroundColor: BASE_COLOUR,
      },
    ],
    [
      "expo-build-properties",
      { ios: { deploymentTarget: "16.4" }, android: { minSdkVersion: 24 } },
    ],
    "react-native-quick-crypto",
    [
      "expo-camera",
      {
        cameraPermission: CAMERA_USAGE,
        microphonePermission: false,
        recordAudioAndroid: false,
        barcodeScannerEnabled: true,
      },
    ],
    ["expo-local-authentication", { faceIDPermission: FACE_ID_USAGE }],
    ["expo-secure-store", { faceIDPermission: FACE_ID_USAGE }],
  ],
};

export default config;
